// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdCT3-RaSS8Hp1iZxa63HFh78AYEGetoM',
    appId: '1:714985489410:web:e3d8effff69ab51f89531b',
    messagingSenderId: '714985489410',
    projectId: 'city-choosing',
    authDomain: 'city-choosing.firebaseapp.com',
    storageBucket: 'city-choosing.firebasestorage.app',
    measurementId: 'G-Q04L5FKZN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpWp9mvR0abAnx2tEGIVnoJmcgT918bfg',
    appId: '1:714985489410:android:aa12da8e0788b5a589531b',
    messagingSenderId: '714985489410',
    projectId: 'city-choosing',
    storageBucket: 'city-choosing.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSeg20avRR2QN5OdU2dPyxTbUHU3EIBOU',
    appId: '1:714985489410:ios:c9a0f5bb426cb64089531b',
    messagingSenderId: '714985489410',
    projectId: 'city-choosing',
    storageBucket: 'city-choosing.firebasestorage.app',
    iosBundleId: 'com.example.cityChoosing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSeg20avRR2QN5OdU2dPyxTbUHU3EIBOU',
    appId: '1:714985489410:ios:c9a0f5bb426cb64089531b',
    messagingSenderId: '714985489410',
    projectId: 'city-choosing',
    storageBucket: 'city-choosing.firebasestorage.app',
    iosBundleId: 'com.example.cityChoosing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdCT3-RaSS8Hp1iZxa63HFh78AYEGetoM',
    appId: '1:714985489410:web:ce6c37ad7bfb0eed89531b',
    messagingSenderId: '714985489410',
    projectId: 'city-choosing',
    authDomain: 'city-choosing.firebaseapp.com',
    storageBucket: 'city-choosing.firebasestorage.app',
    measurementId: 'G-02PLLSFTE8',
  );
}
